[package]
name = "rltk_practice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spec = "0.2.0"
rltk = "0.8.0"
